# Model based on open value

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt 

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
data =pd.read_csv("Cripto_data2.csv")

In [4]:
data

Unnamed: 0        Date         Open         High          Low  \
0              0  2014-10-30   335.709015   350.912994   335.071991   
1              1  2014-10-31   345.009003   348.045013   337.141998   
2              2  2014-11-01   338.649994   340.528992   321.054993   
3              3  2014-11-02   326.075012   329.049988   320.626007   
4              4  2014-11-03   325.569000   334.002014   325.480988   
...          ...         ...          ...          ...          ...   
9520        1528  2022-01-26  1813.814819  1861.973999  1673.215332   
9521        1529  2022-01-27  1706.307983  1787.372925  1655.685669   
9522        1530  2022-01-28  1768.952026  1874.516235  1736.091919   
9523        1531  2022-01-29  1872.410278  1957.882324  1863.551392   
9524        1532  2022-01-30  1950.592407  1971.543213  1940.510376   

            Close    Adj Close       Volume Cripto  
0      345.304993   345.304993   30177900.0    BTC  
1      338.321014   338.321014   12545400.0    BTC  
2      325.748993   325.748993   16677200.0    BTC  
3      325.891998   325.891998    8603620.0    BTC  
4      327.553986   327.553986   12948500.0    BTC  
...           ...          ...          ...    ...  
9520  1706.681885  1706.681885  260720682.0    MKR  
9521  1769.279297  1769.279297  187232810.0    MKR  
9522  1872.471802  1872.471802  219022529.0    MKR  
9523  1948.442749  1948.442749   93560252.0    MKR  
9524  1946.990845  1946.990845  102377872.0    MKR  

[9525 rows x 9 columns]

In [5]:
(1.024230+0.995486)/2

1.009858

In [6]:
data.isnull().any()

Unnamed: 0    False
Date          False
Open           True
High           True
Low            True
Close          True
Adj Close      True
Volume         True
Cripto        False
dtype: bool

In [7]:
data.isnull().sum()

Unnamed: 0    0
Date          0
Open          3
High          3
Low           3
Close         3
Adj Close     3
Volume        3
Cripto        0
dtype: int64

In [8]:
data.dropna(inplace =True)

In [9]:
data.isnull().sum()

Unnamed: 0    0
Date          0
Open          0
High          0
Low           0
Close         0
Adj Close     0
Volume        0
Cripto        0
dtype: int64

In [10]:
data.columns

Index(['Unnamed: 0', 'Date', 'Open', 'High', 'Low', 'Close', 'Adj Close',
       'Volume', 'Cripto'],
      dtype='object')

In [11]:
data.drop(['Unnamed: 0', 'Adj Close','Volume' ],axis =1, inplace =True)

# Make Closeas a target value 

In [12]:
#data["Today_USD"] =  (data["Open"] + data["Close"] ) /2
#data["Today_Close(USD)"] =  (data["Close"])
data

Date         Open         High          Low        Close Cripto
0     2014-10-30   335.709015   350.912994   335.071991   345.304993    BTC
1     2014-10-31   345.009003   348.045013   337.141998   338.321014    BTC
2     2014-11-01   338.649994   340.528992   321.054993   325.748993    BTC
3     2014-11-02   326.075012   329.049988   320.626007   325.891998    BTC
4     2014-11-03   325.569000   334.002014   325.480988   327.553986    BTC
...          ...          ...          ...          ...          ...    ...
9520  2022-01-26  1813.814819  1861.973999  1673.215332  1706.681885    MKR
9521  2022-01-27  1706.307983  1787.372925  1655.685669  1769.279297    MKR
9522  2022-01-28  1768.952026  1874.516235  1736.091919  1872.471802    MKR
9523  2022-01-29  1872.410278  1957.882324  1863.551392  1948.442749    MKR
9524  2022-01-30  1950.592407  1971.543213  1940.510376  1946.990845    MKR

[9522 rows x 6 columns]

In [13]:
# making tomorrow result 
for id, crip in enumerate(data["Cripto"].unique()):
    ind_cript = data[data["Cripto"] == crip]
    ind_cript["Tomorrow_Close(USD)"] =ind_cript["Close"].shift(-1) 
    ind_cript.head()
    ind_cript.dropna(inplace =True)
    if (id ==0 ):
        BTC =ind_cript
    elif (id ==1 ):
        ADA = ind_cript
    elif (id == 2 ):
        BNB = ind_cript
    elif (id == 3 ):
        ETH = ind_cript
    elif (id == 4 ):
        USDT = ind_cript
        

file = pd.concat([BTC,ETH, BNB, ADA, USDT])
#files = pd.concat([BTC,ETH, BNB])

In [14]:
file.head()

Date        Open        High         Low       Close Cripto  \
0  2014-10-30  335.709015  350.912994  335.071991  345.304993    BTC   
1  2014-10-31  345.009003  348.045013  337.141998  338.321014    BTC   
2  2014-11-01  338.649994  340.528992  321.054993  325.748993    BTC   
3  2014-11-02  326.075012  329.049988  320.626007  325.891998    BTC   
4  2014-11-03  325.569000  334.002014  325.480988  327.553986    BTC   

   Tomorrow_Close(USD)  
0           338.321014  
1           325.748993  
2           325.891998  
3           327.553986  
4           330.492004

In [15]:
for x, y in enumerate(data["Cripto"].unique()):
    file["Cripto"] = file["Cripto"].replace({y:  x})
    print("The cripto ", y, " is =", x)
    

The cripto  BTC  is = 0
The cripto  LTC  is = 1
The cripto  BNB  is = 2
The cripto  ETH  is = 3
The cripto  MKR  is = 4


In [16]:
file["Cripto"].unique()

array([0, 3, 2, 1, 4], dtype=int64)

In [17]:
file.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Cripto',
       'Tomorrow_Close(USD)'],
      dtype='object')

In [18]:
file.drop(["Date"], inplace =True, axis =True)

# Scaling

In [19]:
file.head()

Open        High         Low       Close  Cripto  Tomorrow_Close(USD)
0  335.709015  350.912994  335.071991  345.304993       0           338.321014
1  345.009003  348.045013  337.141998  338.321014       0           325.748993
2  338.649994  340.528992  321.054993  325.748993       0           325.891998
3  326.075012  329.049988  320.626007  325.891998       0           327.553986
4  325.569000  334.002014  325.480988  327.553986       0           330.492004

In [20]:
from sklearn.model_selection import train_test_split

X = file.iloc[:,:-1]
Y = file.iloc[:,-1]

In [21]:
from sklearn.preprocessing import MinMaxScaler
#sc = MinMaxScaler()
scaler_x = MinMaxScaler()
scaler_y = MinMaxScaler()

scaler_x.fit(X)
X_sc = scaler_x.transform(X)
Y_sc = scaler_y.fit(file[["Tomorrow_Close(USD)"]])
Y_sc =scaler_y.fit_transform(file[["Tomorrow_Close(USD)"]])
X_sc,Y_sc


(array([[0.00494754, 0.00507836, 0.00502571, 0.00508833, 0.        ],
        [0.00508522, 0.00503667, 0.00505689, 0.00498496, 0.        ],
        [0.00499108, 0.0049274 , 0.00481455, 0.00479889, 0.        ],
        ...,
        [0.02523822, 0.02596077, 0.02492028, 0.02616385, 1.        ],
        [0.02616561, 0.0272276 , 0.02613157, 0.02769115, 1.        ],
        [0.02769723, 0.02843953, 0.0280517 , 0.02881556, 1.        ]]),
 array([[0.00498496],
        [0.00479889],
        [0.00480101],
        ...,
        [0.02769115],
        [0.02881556],
        [0.02879407]]))

In [22]:
X,Y

(             Open         High          Low        Close  Cripto
 0      335.709015   350.912994   335.071991   345.304993       0
 1      345.009003   348.045013   337.141998   338.321014       0
 2      338.649994   340.528992   321.054993   325.748993       0
 3      326.075012   329.049988   320.626007   325.891998       0
 4      325.569000   334.002014   325.480988   327.553986       0
 ...           ...          ...          ...          ...     ...
 9519  1923.388916  1937.598755  1800.128052  1814.199219       4
 9520  1813.814819  1861.973999  1673.215332  1706.681885       4
 9521  1706.307983  1787.372925  1655.685669  1769.279297       4
 9522  1768.952026  1874.516235  1736.091919  1872.471802       4
 9523  1872.410278  1957.882324  1863.551392  1948.442749       4
 
 [9517 rows x 5 columns],
 0        338.321014
 1        325.748993
 2        325.891998
 3        327.553986
 4        330.492004
            ...     
 9519    1706.681885
 9520    1769.279297
 9521    187

In [23]:
#scaler_x.inverse_transform(X_sc)
#scaler_y.inverse_transform(Y_sc)


In [24]:
X_train,X_test, Y_train, Y_test = train_test_split( X_sc, Y_sc,test_size = 0.2, random_state = 42)

# machine learning algarithams comparitions

In [25]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import Lasso
from xgboost import XGBRegressor
from sklearn.linear_model import Ridge 
#from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor 
lr = LinearRegression()
svr =SVR()
sgdr = SGDRegressor()
ls = Lasso()
xgbr = XGBRegressor()
r = Ridge()
rfr = RandomForestRegressor()

alg = [lr, svr, sgdr, ls, xgbr, r,rfr]

In [26]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

from math import sqrt

#rms = sqrt(mean_squared_error(y_actual, y_predicted))

In [27]:
for  x in alg:
    x.fit(X_train, Y_train)
    predict = x.predict(X_test)
    mse = mean_squared_error(Y_test, predict)
    rms = np.sqrt(mse)
    mae = mean_absolute_error(Y_test, predict)
    r2 = r2_score(Y_test, predict)

    print(x,"\n mse = ",mse,";  rms = ",rms," mae = ", mae, "R2 = ",r2)
    print()


LinearRegression() 
 mse =  3.3666146384774134e-05 ;  rms =  0.005802253560882541  mae =  0.0015257394747382694 R2 =  0.9981153520600605

SVR() 
 mse =  0.007093441791641655 ;  rms =  0.08422257293411105  mae =  0.08142895529937454 R2 =  0.6029055328487549

SGDRegressor() 
 mse =  7.99272949153164e-05 ;  rms =  0.008940206648356423  mae =  0.005223211148789624 R2 =  0.9955256295156131

Lasso() 
 mse =  0.0178781579762708 ;  rms =  0.13370922921126574  mae =  0.07024065949232298 R2 =  -0.000828345923456375

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=4,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_a

# Prediction Testiong

In [35]:

lr.fit(X_train, Y_train)
predictlr = lr.predict(X_test)
mse = mean_squared_error(Y_test, predictlr)
rms = np.sqrt(mse)
mae = mean_absolute_error(Y_test, predictlr)
r2 = r2_score(Y_test, predictlr)

print(x,"\n mse = ",mse,";  rms = ",rms," mse = ", mae, "R2 = ",r2)
print()


RandomForestRegressor() 
 mse =  3.3666146384774134e-05 ;  rms =  0.005802253560882541  mse =  0.0015257394747382694 R2 =  0.9981153520600605



In [36]:
scaler_y.inverse_transform(Y_test)[:20]

array([[   32.713165],
       [ 8078.203125],
       [   82.396004],
       [  461.630249],
       [  229.776001],
       [  465.581757],
       [  114.679001],
       [  740.828979],
       [13546.522461],
       [11506.865234],
       [  466.088989],
       [  130.056656],
       [  493.164795],
       [ 7550.900879],
       [   56.041016],
       [  545.331543],
       [ 2705.409912],
       [10868.400391],
       [  579.513489],
       [ 6773.879883]])

In [37]:
scaler_y.inverse_transform(predictlrr)[:20]

array([[   38.28266664],
       [ 8243.34511786],
       [   95.62326838],
       [  491.2532455 ],
       [  230.21831033],
       [  450.44145314],
       [  141.27218067],
       [  741.82048075],
       [13432.39795143],
       [11532.70216509],
       [  474.40106141],
       [  135.27151299],
       [  494.48062419],
       [ 7427.06766694],
       [   67.84353404],
       [  547.90556221],
       [ 2699.83786217],
       [10971.14250797],
       [  590.60388034],
       [ 6857.61076515]])

In [38]:
z= []
for x in (file.iloc[:,:-1].columns):
    print("Enter ",x, "value")
    a= input()
    z.append(a)
print("input is :" , z )

Enter  Open value
5
Enter  High value
5
Enter  Low value
5
Enter  Close value
5
Enter  Cripto value
0
input is : ['5', '5', '5', '5', '0']


In [40]:
a =[1,2,3,4,5]
A =np.array([z])
#A.shape
test_input = scaler_x.transform(A)# input to 
print("our enterd input ")
pred =lr.predict(test_input)# predicting 
real = scaler_y.inverse_transform(pred) #insverse scaling
pred


our enterd input 


array([[0.00025404]])

In [41]:
import joblib
joblib.dump(lr,"Close_lr_sc.pkl")

['Close_lr_sc.pkl']