# Model based on open value

In [28]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt 

In [29]:
import warnings
warnings.filterwarnings("ignore")

In [30]:
data =pd.read_csv("Cripto_data2.csv")

In [31]:
data

Unnamed: 0        Date         Open         High          Low  \
0              0  2014-10-30   335.709015   350.912994   335.071991   
1              1  2014-10-31   345.009003   348.045013   337.141998   
2              2  2014-11-01   338.649994   340.528992   321.054993   
3              3  2014-11-02   326.075012   329.049988   320.626007   
4              4  2014-11-03   325.569000   334.002014   325.480988   
...          ...         ...          ...          ...          ...   
9520        1528  2022-01-26  1813.814819  1861.973999  1673.215332   
9521        1529  2022-01-27  1706.307983  1787.372925  1655.685669   
9522        1530  2022-01-28  1768.952026  1874.516235  1736.091919   
9523        1531  2022-01-29  1872.410278  1957.882324  1863.551392   
9524        1532  2022-01-30  1950.592407  1971.543213  1940.510376   

            Close    Adj Close       Volume Cripto  
0      345.304993   345.304993   30177900.0    BTC  
1      338.321014   338.321014   12545400.0    BTC  
2      325.748993   325.748993   16677200.0    BTC  
3      325.891998   325.891998    8603620.0    BTC  
4      327.553986   327.553986   12948500.0    BTC  
...           ...          ...          ...    ...  
9520  1706.681885  1706.681885  260720682.0    MKR  
9521  1769.279297  1769.279297  187232810.0    MKR  
9522  1872.471802  1872.471802  219022529.0    MKR  
9523  1948.442749  1948.442749   93560252.0    MKR  
9524  1946.990845  1946.990845  102377872.0    MKR  

[9525 rows x 9 columns]

In [32]:
(1.024230+0.995486)/2

1.009858

In [33]:
data.isnull().any()

Unnamed: 0    False
Date          False
Open           True
High           True
Low            True
Close          True
Adj Close      True
Volume         True
Cripto        False
dtype: bool

In [34]:
data.isnull().sum()

Unnamed: 0    0
Date          0
Open          3
High          3
Low           3
Close         3
Adj Close     3
Volume        3
Cripto        0
dtype: int64

In [35]:
data.dropna(inplace =True)

In [36]:
data.isnull().sum()

Unnamed: 0    0
Date          0
Open          0
High          0
Low           0
Close         0
Adj Close     0
Volume        0
Cripto        0
dtype: int64

In [37]:
data.columns

Index(['Unnamed: 0', 'Date', 'Open', 'High', 'Low', 'Close', 'Adj Close',
       'Volume', 'Cripto'],
      dtype='object')

In [38]:
data.drop(['Unnamed: 0', 'Adj Close','Volume' ],axis =1, inplace =True)
#data

# Make Closeas a target value 

In [39]:
#data["Today_USD"] =  (data["Open"] + data["Close"] ) /2
#data["Today_Close(USD)"] =  (data["Close"])


In [40]:
# making tomorrow result 
for id, crip in enumerate(data["Cripto"].unique()):
    ind_cript = data[data["Cripto"] == crip]
    ind_cript["Tomorrow_High(USD)"] =ind_cript["High"].shift(-1) 
    ind_cript.head()
    ind_cript.dropna(inplace =True)
    if (id ==0 ):
        BTC =ind_cript
    elif (id ==1 ):
        ADA = ind_cript
    elif (id == 2 ):
        BNB = ind_cript
    elif (id == 3 ):
        ETH = ind_cript
    elif (id == 4 ):
        USDT = ind_cript
        

file = pd.concat([BTC,ETH, BNB, ADA, USDT])
#files = pd.concat([BTC,ETH, BNB])

In [41]:
file.head()

Date        Open        High         Low       Close Cripto  \
0  2014-10-30  335.709015  350.912994  335.071991  345.304993    BTC   
1  2014-10-31  345.009003  348.045013  337.141998  338.321014    BTC   
2  2014-11-01  338.649994  340.528992  321.054993  325.748993    BTC   
3  2014-11-02  326.075012  329.049988  320.626007  325.891998    BTC   
4  2014-11-03  325.569000  334.002014  325.480988  327.553986    BTC   

   Tomorrow_High(USD)  
0          348.045013  
1          340.528992  
2          329.049988  
3          334.002014  
4          331.766998

In [42]:
for x, y in enumerate(data["Cripto"].unique()):
    file["Cripto"] = file["Cripto"].replace({y:  x})
    print("The cripto ", y, " is =", x)
    

The cripto  BTC  is = 0
The cripto  LTC  is = 1
The cripto  BNB  is = 2
The cripto  ETH  is = 3
The cripto  MKR  is = 4


In [43]:
file["Cripto"].unique()

array([0, 3, 2, 1, 4], dtype=int64)

In [44]:
file.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Cripto', 'Tomorrow_High(USD)'], dtype='object')

In [45]:
file.drop(["Date"], inplace =True, axis =True)

# Scaling

In [46]:
file.head()

Open        High         Low       Close  Cripto  Tomorrow_High(USD)
0  335.709015  350.912994  335.071991  345.304993       0          348.045013
1  345.009003  348.045013  337.141998  338.321014       0          340.528992
2  338.649994  340.528992  321.054993  325.748993       0          329.049988
3  326.075012  329.049988  320.626007  325.891998       0          334.002014
4  325.569000  334.002014  325.480988  327.553986       0          331.766998

# machine learning algarithams comparitions

In [47]:
from sklearn.model_selection import train_test_split

X = file.iloc[:,:-1]
Y = file.iloc[:,-1]

In [48]:
y =np.array([Y]).T.shape

In [49]:
from sklearn.preprocessing import MinMaxScaler
#sc = MinMaxScaler()
scaler_x = MinMaxScaler()
scaler_y = MinMaxScaler()

scaler_x.fit(X)
X_sc = scaler_x.transform(X)
Y_sc = scaler_y.fit(file[["Tomorrow_High(USD)"]])
Y_sc =scaler_y.fit_transform(file[["Tomorrow_High(USD)"]])
X_sc,Y_sc


(array([[0.00494754, 0.00507836, 0.00502571, 0.00508833, 0.        ],
        [0.00508522, 0.00503667, 0.00505689, 0.00498496, 0.        ],
        [0.00499108, 0.0049274 , 0.00481455, 0.00479889, 0.        ],
        ...,
        [0.02523822, 0.02596077, 0.02492028, 0.02616385, 1.        ],
        [0.02616561, 0.0272276 , 0.02613157, 0.02769115, 1.        ],
        [0.02769723, 0.02843953, 0.0280517 , 0.02881556, 1.        ]]),
 array([[0.00503667],
        [0.0049274 ],
        [0.00476053],
        ...,
        [0.0272276 ],
        [0.02843953],
        [0.02863812]]))

In [50]:
X,Y

(             Open         High          Low        Close  Cripto
 0      335.709015   350.912994   335.071991   345.304993       0
 1      345.009003   348.045013   337.141998   338.321014       0
 2      338.649994   340.528992   321.054993   325.748993       0
 3      326.075012   329.049988   320.626007   325.891998       0
 4      325.569000   334.002014   325.480988   327.553986       0
 ...           ...          ...          ...          ...     ...
 9519  1923.388916  1937.598755  1800.128052  1814.199219       4
 9520  1813.814819  1861.973999  1673.215332  1706.681885       4
 9521  1706.307983  1787.372925  1655.685669  1769.279297       4
 9522  1768.952026  1874.516235  1736.091919  1872.471802       4
 9523  1872.410278  1957.882324  1863.551392  1948.442749       4
 
 [9517 rows x 5 columns],
 0        348.045013
 1        340.528992
 2        329.049988
 3        334.002014
 4        331.766998
            ...     
 9519    1861.973999
 9520    1787.372925
 9521    187

In [51]:
#scaler_x.inverse_transform(X_sc)
#scaler_y.inverse_transform(Y_sc)


In [52]:
X_train,X_test, Y_train, Y_test = train_test_split( X, Y,test_size = 0.2, random_state = 42)

In [53]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import Lasso
from xgboost import XGBRegressor
from sklearn.linear_model import Ridge 
#from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor 
lr = LinearRegression()
svr =SVR()
sgdr = SGDRegressor()
ls = Lasso()
xgbr = XGBRegressor()
r = Ridge()
rfr = RandomForestRegressor()

alg = [lr, svr, sgdr, ls, xgbr, r,rfr]

In [54]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

from math import sqrt

#rms = sqrt(mean_squared_error(y_actual, y_predicted))

In [55]:
for  x in alg:
    x.fit(X_train, Y_train)
    predict = x.predict(X_test)
    mse = mean_squared_error(Y_test, predict)
    rms = np.sqrt(mse)
    mae = mean_absolute_error(Y_test, predict)
    r2 = r2_score(Y_test, predict)

    print(x,"\n mse = ",mse,";  rms = ",rms," mae = ", mae, "R2 = ",r2)
    print()


LinearRegression() 
 mse =  68937.77823509641 ;  rms =  262.5600469132659  mae =  75.27828153632478 R2 =  0.9991948607985696

SVR() 
 mse =  88744151.22186966 ;  rms =  9420.411414681934  mae =  3035.7103348281253 R2 =  -0.03646210939272709

SGDRegressor() 
 mse =  1.730230683108928e+34 ;  rms =  1.315382333433488e+17  mae =  4.519978017232247e+16 R2 =  -2.0207737849310364e+26

Lasso() 
 mse =  87279.5207394444 ;  rms =  295.4310761234241  mae =  83.23261834637705 R2 =  0.9989806436263475

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=4,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
         

# Prediction Testiong

In [56]:

lr.fit(X_train, Y_train)
predictlr = lr.predict(X_test)
mse = mean_squared_error(Y_test, predictlr)
rms = np.sqrt(mse)
mae = mean_absolute_error(Y_test, predictlr)
r2 = r2_score(Y_test, predictlr)

print(x,"\n mse = ",mse,";  rms = ",rms," mse = ", mae, "R2 = ",r2)
print()


RandomForestRegressor() 
 mse =  68937.77823509641 ;  rms =  262.5600469132659  mse =  75.27828153632478 R2 =  0.9991948607985696



In [57]:
predictlr[:15]

array([   39.71692895,  8412.1135607 ,    91.97728635,   519.58495091,
         247.67305935,   475.2952058 ,   138.83203075,   747.78675151,
       13776.13178933, 11784.49989713,   472.62907496,   141.15223116,
         522.15616228,  7613.76488261,    63.12721788])

In [58]:
Y_test[:15]

5506       33.640659
1817     8296.651367
3600       86.678101
8747      497.416962
7060      235.025650
8963      469.224579
3499      132.610001
733       740.828979
2191    13651.516602
2129    11585.640625
543       467.964996
6098      133.280609
8692      502.681152
2002     7574.195801
4381       59.159904
Name: Tomorrow_High(USD), dtype: float64

In [59]:
#test = np.array([predictlr]).T
#predictlr

In [60]:
#scaler_y.inverse_transform(Y_test)[:20]

In [61]:
#scaler_y.inverse_transform(predictlr)[:20]

# Manual input

In [64]:
z= []
for x in (X_train.columns):
    print("Enter ",x, "value")
    
    a= input()
    z.append(a)
print("input is :" , z )

Enter  Open value
4
Enter  High value
4
Enter  Low value
4
Enter  Close value
4
Enter  Cripto value
4
input is : ['4', '4', '4', '4', '4']


In [65]:
Z =np.array([z])

In [66]:
#a =[1,2,3,4,5]
#A =np.array([a])
#A.shape
#test_input = scaler_x.transform(A)# input to 
#print("our enterd input ")
pred =lr.predict(Z)# predicting 
#real = scaler_y.inverse_transform(pred) #insverse scaling
pred


array([15.2601089])

In [70]:
import joblib
joblib.dump(lr,"High_lr.pkl")

['High_lr.pkl']

In [68]:
high = joblib.load("High_lr.pkl")

In [69]:
high.predict(Z)

array([15.2601089])