# Model based on open value

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt 

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
data =pd.read_csv("Cripto_data2.csv")

In [4]:
data

Unnamed: 0        Date         Open         High          Low  \
0              0  2014-10-30   335.709015   350.912994   335.071991   
1              1  2014-10-31   345.009003   348.045013   337.141998   
2              2  2014-11-01   338.649994   340.528992   321.054993   
3              3  2014-11-02   326.075012   329.049988   320.626007   
4              4  2014-11-03   325.569000   334.002014   325.480988   
...          ...         ...          ...          ...          ...   
9520        1528  2022-01-26  1813.814819  1861.973999  1673.215332   
9521        1529  2022-01-27  1706.307983  1787.372925  1655.685669   
9522        1530  2022-01-28  1768.952026  1874.516235  1736.091919   
9523        1531  2022-01-29  1872.410278  1957.882324  1863.551392   
9524        1532  2022-01-30  1950.592407  1971.543213  1940.510376   

            Close    Adj Close       Volume Cripto  
0      345.304993   345.304993   30177900.0    BTC  
1      338.321014   338.321014   12545400.0    BTC  
2      325.748993   325.748993   16677200.0    BTC  
3      325.891998   325.891998    8603620.0    BTC  
4      327.553986   327.553986   12948500.0    BTC  
...           ...          ...          ...    ...  
9520  1706.681885  1706.681885  260720682.0    MKR  
9521  1769.279297  1769.279297  187232810.0    MKR  
9522  1872.471802  1872.471802  219022529.0    MKR  
9523  1948.442749  1948.442749   93560252.0    MKR  
9524  1946.990845  1946.990845  102377872.0    MKR  

[9525 rows x 9 columns]

In [5]:
data.isnull().any()

Unnamed: 0    False
Date          False
Open           True
High           True
Low            True
Close          True
Adj Close      True
Volume         True
Cripto        False
dtype: bool

In [6]:
data.isnull().sum()

Unnamed: 0    0
Date          0
Open          3
High          3
Low           3
Close         3
Adj Close     3
Volume        3
Cripto        0
dtype: int64

In [7]:
data.dropna(inplace =True)

In [8]:
data.isnull().sum()

Unnamed: 0    0
Date          0
Open          0
High          0
Low           0
Close         0
Adj Close     0
Volume        0
Cripto        0
dtype: int64

In [9]:
data.columns

Index(['Unnamed: 0', 'Date', 'Open', 'High', 'Low', 'Close', 'Adj Close',
       'Volume', 'Cripto'],
      dtype='object')

In [10]:
data.drop(['Unnamed: 0', 'Adj Close','Volume' ],axis =1, inplace =True)
data

Date         Open         High          Low        Close Cripto
0     2014-10-30   335.709015   350.912994   335.071991   345.304993    BTC
1     2014-10-31   345.009003   348.045013   337.141998   338.321014    BTC
2     2014-11-01   338.649994   340.528992   321.054993   325.748993    BTC
3     2014-11-02   326.075012   329.049988   320.626007   325.891998    BTC
4     2014-11-03   325.569000   334.002014   325.480988   327.553986    BTC
...          ...          ...          ...          ...          ...    ...
9520  2022-01-26  1813.814819  1861.973999  1673.215332  1706.681885    MKR
9521  2022-01-27  1706.307983  1787.372925  1655.685669  1769.279297    MKR
9522  2022-01-28  1768.952026  1874.516235  1736.091919  1872.471802    MKR
9523  2022-01-29  1872.410278  1957.882324  1863.551392  1948.442749    MKR
9524  2022-01-30  1950.592407  1971.543213  1940.510376  1946.990845    MKR

[9522 rows x 6 columns]

# Make Closeas a target value 

In [11]:
#data["Today_USD"] =  (data["Open"] + data["Close"] ) /2
#data["Today_Close(USD)"] =  (data["Close"])


In [12]:
# making tomorrow result 
for id, crip in enumerate(data["Cripto"].unique()):
    ind_cript = data[data["Cripto"] == crip]
    ind_cript["Tomorrow_Low(USD)"] =ind_cript["Low"].shift(-1) 
    ind_cript.head()
    ind_cript.dropna(inplace =True)
    if (id ==0 ):
        BTC =ind_cript
    elif (id ==1 ):
        ADA = ind_cript
    elif (id == 2 ):
        BNB = ind_cript
    elif (id == 3 ):
        ETH = ind_cript
    elif (id == 4 ):
        USDT = ind_cript
        

file = pd.concat([BTC,ETH, BNB, ADA, USDT])
#files = pd.concat([BTC,ETH, BNB])

In [13]:
file.head()

Date        Open        High         Low       Close Cripto  \
0  2014-10-30  335.709015  350.912994  335.071991  345.304993    BTC   
1  2014-10-31  345.009003  348.045013  337.141998  338.321014    BTC   
2  2014-11-01  338.649994  340.528992  321.054993  325.748993    BTC   
3  2014-11-02  326.075012  329.049988  320.626007  325.891998    BTC   
4  2014-11-03  325.569000  334.002014  325.480988  327.553986    BTC   

   Tomorrow_Low(USD)  
0         337.141998  
1         321.054993  
2         320.626007  
3         325.480988  
4         325.076996

In [14]:
for x, y in enumerate(data["Cripto"].unique()):
    file["Cripto"] = file["Cripto"].replace({y:  x})
    print("The cripto ", y, " is =", x)
    

The cripto  BTC  is = 0
The cripto  LTC  is = 1
The cripto  BNB  is = 2
The cripto  ETH  is = 3
The cripto  MKR  is = 4


In [15]:
file["Cripto"].unique()

array([0, 3, 2, 1, 4], dtype=int64)

In [16]:
file.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Cripto', 'Tomorrow_Low(USD)'], dtype='object')

In [17]:
file.drop(["Date"], inplace =True, axis =True)

# Scaling

In [18]:
file.head()

Open        High         Low       Close  Cripto  Tomorrow_Low(USD)
0  335.709015  350.912994  335.071991  345.304993       0         337.141998
1  345.009003  348.045013  337.141998  338.321014       0         321.054993
2  338.649994  340.528992  321.054993  325.748993       0         320.626007
3  326.075012  329.049988  320.626007  325.891998       0         325.480988
4  325.569000  334.002014  325.480988  327.553986       0         325.076996

In [19]:
from sklearn.model_selection import train_test_split

X = file.iloc[:,:-1]
Y = file.iloc[:,-1]

In [20]:
y =np.array([Y]).T.shape

In [21]:
from sklearn.preprocessing import MinMaxScaler
#sc = MinMaxScaler()
scaler_x = MinMaxScaler()
scaler_y = MinMaxScaler()

scaler_x.fit(X)
X_sc = scaler_x.transform(X)
Y_sc = scaler_y.fit(file[["Tomorrow_Low(USD)"]])
Y_sc =scaler_y.fit_transform(file[["Tomorrow_Low(USD)"]])
X_sc,Y_sc


(array([[0.00494754, 0.00507836, 0.00502571, 0.00508833, 0.        ],
        [0.00508522, 0.00503667, 0.00505689, 0.00498496, 0.        ],
        [0.00499108, 0.0049274 , 0.00481455, 0.00479889, 0.        ],
        ...,
        [0.02523822, 0.02596077, 0.02492028, 0.02616385, 1.        ],
        [0.02616561, 0.0272276 , 0.02613157, 0.02769115, 1.        ],
        [0.02769723, 0.02843953, 0.0280517 , 0.02881556, 1.        ]]),
 array([[0.00505689],
        [0.00481455],
        [0.00480808],
        ...,
        [0.02613157],
        [0.0280517 ],
        [0.02921106]]))

In [40]:
X.head()

Open        High         Low       Close  Cripto
0  335.709015  350.912994  335.071991  345.304993       0
1  345.009003  348.045013  337.141998  338.321014       0
2  338.649994  340.528992  321.054993  325.748993       0
3  326.075012  329.049988  320.626007  325.891998       0
4  325.569000  334.002014  325.480988  327.553986       0

In [23]:
#scaler_x.inverse_transform(X_sc)
#scaler_y.inverse_transform(Y_sc)


In [24]:
X_train,X_test, Y_train, Y_test = train_test_split( X_sc, Y_sc,test_size = 0.2, random_state = 42)

# machine learning algarithams comparitions

In [25]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import Lasso
from xgboost import XGBRegressor
from sklearn.linear_model import Ridge 
#from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor 
lr = LinearRegression()
svr =SVR()
sgdr = SGDRegressor()
ls = Lasso()
xgbr = XGBRegressor()
r = Ridge()
rfr = RandomForestRegressor()

alg = [lr, svr, sgdr, ls, xgbr, r,rfr]

In [26]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

from math import sqrt

#rms = sqrt(mean_squared_error(y_actual, y_predicted))

In [27]:
for  x in alg:
    x.fit(X_train, Y_train)
    predict = x.predict(X_test)
    mse = mean_squared_error(Y_test, predict)
    rms = np.sqrt(mse)
    mae = mean_absolute_error(Y_test, predict)
    r2 = r2_score(Y_test, predict)

    print(x,"\n mse = ",mse,";  rms = ",rms," mae = ", mae, "R2 = ",r2)
    print()


LinearRegression() 
 mse =  2.660155043983502e-05 ;  rms =  0.0051576690897957985  mae =  0.0012139411026700273 R2 =  0.9984699366707951

SVR() 
 mse =  0.007098556490771532 ;  rms =  0.08425293164496729  mae =  0.08127626028413316 R2 =  0.5917064683359663

SGDRegressor() 
 mse =  7.70177972028582e-05 ;  rms =  0.008775978418550162  mae =  0.005117175179132887 R2 =  0.9955701038004247

Lasso() 
 mse =  0.017400206482418242 ;  rms =  0.13190984224999378  mae =  0.06929974288462105 R2 =  -0.0008220355259569434

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=4,
             num_parallel_tree=1, predictor='auto', random_state=0, re

# Prediction Testiong

In [28]:

lr.fit(X_train, Y_train)
predictlr = lr.predict(X_test)
mse = mean_squared_error(Y_test, predictlr)
rms = np.sqrt(mse)
mae = mean_absolute_error(Y_test, predictlr)
r2 = r2_score(Y_test, predictlr)

print(x,"\n mse = ",mse,";  rms = ",rms," mse = ", mae, "R2 = ",r2)
print()


RandomForestRegressor() 
 mse =  2.660155043983502e-05 ;  rms =  0.0051576690897957985  mse =  0.0012139411026700273 R2 =  0.9984699366707951



In [29]:
predictlr[:15]

array([[0.000491  ],
       [0.12170945],
       [0.00135402],
       [0.00702258],
       [0.00313215],
       [0.00650295],
       [0.00201677],
       [0.01085984],
       [0.19657738],
       [0.17003092],
       [0.00696406],
       [0.00185398],
       [0.00708714],
       [0.10862291],
       [0.00095608]])

In [30]:
Y_test[:15]

array([[0.00046674],
       [0.12161686],
       [0.00121601],
       [0.00677324],
       [0.00314744],
       [0.0067472 ],
       [0.00169434],
       [0.0108599 ],
       [0.1978701 ],
       [0.17271357],
       [0.00693212],
       [0.00188811],
       [0.00735847],
       [0.11197125],
       [0.00080344]])

In [31]:
test = np.array([predictlr]).T
predictlr

array([[0.000491  ],
       [0.12170945],
       [0.00135402],
       ...,
       [0.0382039 ],
       [0.00097859],
       [0.00059518]])

In [32]:
scaler_y.inverse_transform(Y_test)[:20]

array([[   32.445293],
       [ 8074.462891],
       [   82.181999],
       [  451.074066],
       [  210.391266],
       [  449.345459],
       [  113.933998],
       [  722.348999],
       [13136.198242],
       [11466.292969],
       [  461.621002],
       [  126.796638],
       [  489.922119],
       [ 7434.181641],
       [   54.795097],
       [  532.094055],
       [ 2642.360107],
       [10129.700195],
       [  572.07135 ],
       [ 6747.97998 ]])

In [33]:
scaler_y.inverse_transform(predictlr)[:20]

array([[   34.05543597],
       [ 8080.60878025],
       [   91.3433233 ],
       [  467.62538897],
       [  209.37650773],
       [  433.13197939],
       [  135.33716027],
       [  722.34530914],
       [13050.38689598],
       [11288.21703734],
       [  463.74117794],
       [  124.53066223],
       [  471.911239  ],
       [ 7211.91622098],
       [   64.9280103 ],
       [  521.20746309],
       [ 2627.46140828],
       [10321.32730456],
       [  567.59939674],
       [ 6675.05113965]])

# Manual input

In [34]:
z= []
for x in (file.iloc[:,:-1].columns):
    print("Enter ",x, "value")
    a= input()
    z.append(a)
print("input is :" , z )

Enter  Open value
4
Enter  High value
4
Enter  Low value
4
Enter  Close value
4
Enter  Cripto value
4
input is : ['4', '4', '4', '4', '4']


In [35]:
Z =np.array([z])

In [36]:
a =[1,2,3,4,5]
A =np.array([a])
A.shape
test_input = scaler_x.transform(A)# input to 
print("our enterd input ")
pred =lr.predict(test_input)# predicting 
real = scaler_y.inverse_transform(pred) #insverse scaling
real


our enterd input 


array([[-11.32193608]])

In [37]:
import joblib
joblib.dump(lr,"Low_lr_sc.pkl")

['Low_lr_sc.pkl']